### ISSUE TITLE
unlocked*Initial cannot be started in initserver, breaks SP

### ISSUE THREAD

**Issue by aefreedman** [nateberkopec/antistasi#60]
You get this if you load a save from pre-arsenal overhaul.

[arma3_2016-12-01_20-52-0.txt](https://github.com/SpaceHunnies/antistasi/files/626212/arma3_2016-12-01_20-52-0.txt)

(Error is super long and makes this input field lag)

Maybe minor but save-breaking is something to be watchful of.

**Comment by nateberkopec** [comment]
Weird...that error doesnt make any sense.

**Comment by nateberkopec** [comment]
Was this in SP? I think I broke SP.

**Comment by aefreedman** [comment]
Yeah I believe so.

**Comment by nateberkopec** [comment]
Yeah, this is me breaking SP, not breaking vanilla saves. Will fix.
