### ISSUE TITLE
APC is still a tank and costs $10,000

### ISSUE THREAD

**Issue by aefreedman** [nateberkopec/antistasi#74]
I have no idea why it costs $10,000

**Comment by nateberkopec** [comment]
It's tracked? It should be a BTR-60.

**Comment by nateberkopec** [comment]
http://www.rhsmods.org/w/btr60%20

**Comment by aefreedman** [comment]
It's the mini-tank with the missile. The same one it was before.

**Comment by nateberkopec** [comment]
I think you might be running a different version then. The metis classname is not present on master.

**Comment by nateberkopec** [comment]
Shit, you're right. I changed the wrong one. Not sure why its 10k.

**Comment by nateberkopec** [comment]
fixed by de6097d0fe350cec7
